name: Java CI with Maven

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: '8.0.412+8'
          distribution: 'temurin'
          cache: maven

      - name: Build, Test, Checkstyle
        run: mvn clean verify checkstyle:check -f roman-number/pom.xml

      - name: Generate JaCoCo Report
        run: mvn jacoco:report -f roman-number/pom.xml

      - name: Report to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: mvn coveralls:report -f roman-number/pom.xml
